### ISSUE TITLE
Multiline selection errors with test command ("unexpected argument")

### ISSUE THREAD

**Issue by Jiogo18** [daleeidd/natural-selection#12]
Fish version: 3.7.0
Natural Selection version: latest commit (2023-11-27)

Selecting multiple lines tries to execute the lines and gives an error.

## How to reproduce
![image](https://github.com/daleeidd/natural-selection/assets/30299784/ec5ea8ec-b2d2-4dc1-9be0-b68904bc018c)

After selecting 2 chars or more on the left:
![image](https://github.com/daleeidd/natural-selection/assets/30299784/a9a2afd7-ae17-4fef-8751-688ad134c0c8)

## Source

https://github.com/daleeidd/natural-selection/blob/ecd61acd210348315ab737c409eac5baa476ea04/functions/_natural_selection.fish#L46
Here, the second line selected is not used as an argument of `test -z` because of the \n.
It does something like this
![image](https://github.com/daleeidd/natural-selection/assets/30299784/693c4492-50bf-4c4f-aea8-09d7c48dada9)

## Solution

I don't know fish enough. In the idea, it should be something like `if test -z "$(commandline --current-selection)"`.
I don't know if other functions are affected by this.

**Comment by magenta404** [comment]
Thank you for the detailed report. All fixed with latest commit.
