### ISSUE TITLE
Compatablity with Autopair

### ISSUE THREAD

**Issue by DrymarchonShaun** [daleeidd/natural-selection#4]
Keybindings overlap between this plugin and [https://github.com/jorgebucaran/autopair.fish](https://github.com/jorgebucaran/autopair.fish). I'm trying to figure out if there's a trick to use them at the same time?

**Comment by magenta404** [comment]
It would need an integration on their end unfortunately.

I wouldn't try asking for integrations at this point as there has been some interest lately in having something like Natural Selection implemented in Fish so hopefully that happens 🤞

**Comment by DrymarchonShaun** [comment]
> some interest lately in having something like Natural Selection implemented in Fish

That would be amazing, lets hope it happens. Is there an issue somewhere about it?

**Comment by magenta404** [comment]
Here: https://github.com/fish-shell/fish-shell/issues/8677

**Comment by blueray453** [comment]
> Keybindings overlap between this plugin and https://github.com/jorgebucaran/autopair.fish. I'm trying to figure out if there's a trick to use them at the same time?

Please check https://github.com/blueray453/natural-selection-autopair.fish
