### ISSUE TITLE
Select All With Ctrl+A

### ISSUE THREAD

**Issue by blueray453** [daleeidd/natural-selection#5]
If I use the following binding then it selects all

    bind \ca '_natural_selection beginning-of-buffer begin-selection end-of-buffer --is-selecting' # ctrl + a

However, when I use backspace or delete, it does not delete the selection.

What to do here?

**Comment by magenta404** [comment]
That won't work for a few reasons:

1. [You cannot mix functions with special input functions](https://fishshell.com/docs/current/cmds/bind.html)
2. NS is not compatible with built-in input functions like begin-selection. It uses it internally but we need to track selection state

You'll want to bind a custom function which has the following:

```fish
commandline --function beginning-of-buffer
_natural_selection_begin_selection
commandline --function end-of-buffer
```

The API is documented in the readme if you need to make more.

**Comment by blueray453** [comment]
Thank you very much.
